<?php declare( strict_types = 1 );
namespace CodeKandis\HotDoc\Frontend\Templates\Plain\Common;

use CodeKandis\HotDoc\Frontend\Templates\Components\ComponentStyles;
use CodeKandis\HotDoc\Frontend\Templates\Components\FormComponent;
use CodeKandis\HotDoc\Frontend\Templates\Components\PasswordInputComponent;
use CodeKandis\HotDoc\Frontend\Templates\Components\SubmitButtonComponent;
use CodeKandis\HotDoc\Frontend\Templates\Components\TextInputComponent;
use CodeKandis\HotDoc\Frontend\Templates\Generators\SignedOutHeaderContentGenerator;
use CodeKandis\Tiphy\Http\Requests\Methods;

/**
 * @var string $requestUri
 */
$requestUri = $this->data[ 'requestUri' ];

$additionalFollowingLinkedStylesheets = [
	'/assets/css/sign-in.css'
];

$headerContent = ( new SignedOutHeaderContentGenerator() )
	->generate();

$contentContent = ( new FormComponent(
	'signIn',
	[],
	[],
	ComponentStyles::DEFAULT,
	'Sign In',
	'h2',
	$requestUri,
	Methods::POST,
	[
		new TextInputComponent( 'div', null, [], [], ComponentStyles::DEFAULT, null, null, 'eMail', 'E-Mail', null ),
		new PasswordInputComponent( 'div', null, [], [], ComponentStyles::DEFAULT, null, null, 'password', 'Password', null ),
		new SubmitButtonComponent( 'div', null, [ 'color-orange' ], [], ComponentStyles::DEFAULT, null, null, 'Sign In' )
	]
) )
	->render();

require __DIR__ . '/Common/html-document-header.phtml';
require __DIR__ . '/Common/html-document-body.phtml';
require __DIR__ . '/Common/html-document-footer.phtml';
