<?php declare( strict_types = 1 );
namespace CodeKandis\HotDoc\Frontend\Templates\Plain\Common;

use CodeKandis\HotDoc\Frontend\Templates\Generators\BookSelectHtmlGenerator;
use CodeKandis\JsonCodec\JsonEncoder;
use CodeKandis\JsonCodec\JsonEncoderOptions;
use ParsedownToC;
use function file_get_contents;

$parsedownToC = new ParsedownToC();

$contentContent = $parsedownToC->text(
	file_get_contents(
		sprintf(
			'%s.md',
			$this->data[ 'documentPath' ]
		)
	)
);

$sidebarLeftContent = sprintf(
	<<<END
		<h2>Books</h2>
		%s
		<div></div>
	END,
	( new BookSelectHtmlGenerator( $this->data[ 'books' ] ) )
		->generate()
);

$sidebarRightContent = sprintf(
	<<<END
		<h2>Table Of Contents</h2>
		%s
	END,
	$parsedownToC->contentsList()
);

$booksJsonData = ( new JsonEncoder() )
	->encode(
		$this->data[ 'books' ],
		new JsonEncoderOptions( JsonEncoderOptions::PRETTY_PRINT )
	);

$additionalFollowingLinkedModularJavaScripts = [
	'/assets/js/application/Pages/ShowBook.js'
];
$additionalPrecedingInlineJavaScripts        = [
	<<<END
		const books = {$booksJsonData};
	END
];

$additionalFollowingLinkedStylesheets = [
	'/assets/css/markdown.css'
];

require __DIR__ . '/Common/html-document-header.phtml';
require __DIR__ . '/Common/html-document-body.phtml';
require __DIR__ . '/Common/html-document-footer.phtml';
