<?php declare( strict_types = 1 );
namespace CodeKandis\HotDoc\Frontend\Templates\Plain\Common;

use CodeKandis\HotDoc\Frontend\Templates\Generators\SignedOutHeaderContentGenerator;

/**
 * @var string $requestUri
 */
$requestUri = $this->data[ 'requestUri' ];

$additionalFollowingLinkedStylesheets = [
	'/assets/css/sign-in.css'
];

$headerContent = ( new SignedOutHeaderContentGenerator() )
	->generate();

$contentContent = <<<END
	<form id="signIn" data-component-type="FORM" data-component-style="DEFAULT" action="{$requestUri}" method="post" enctype="application/x-www-form-urlencoded">
	    <div data-component-subtype="HEADER">
		    <h2>Sign In</h2>
	    </div>
	    <div data-component-subtype="BODY">
			<div data-component-type="INPUT_TEXT" data-component-style="DEFAULT">
				<input name="eMail" type="text" placeholder="E-Mail"/>
			</div>
			<div data-component-type="INPUT_PASSWORD" data-component-style="DEFAULT">
				<input name="password" type="password" placeholder="Password"/>
			</div>
			<div data-component-type="INPUT_SUBMIT" data-component-style="DEFAULT">
				<input class="color-green" type="submit" value="Sign In"/>
			</div>
		</div>
	</form>
END;

require __DIR__ . '/Common/html-document-header.phtml';
require __DIR__ . '/Common/html-document-body.phtml';
require __DIR__ . '/Common/html-document-footer.phtml';
