<?php declare( strict_types = 1 );
namespace CodeKandis\HotDoc\Frontend\Templates\Plain\Common;

use CodeKandis\HotDoc\Configurations\FrontendConfigurationRegistry;
use CodeKandis\HotDoc\Environment\Entities\BookEntityInterface;
use CodeKandis\HotDoc\Environment\Entities\Collections\BookEntityCollectionInterface;
use CodeKandis\HotDoc\Environment\Entities\UserEntityInterface;
use CodeKandis\HotDoc\Frontend\Http\UriBuilders\FrontendUriBuilder;
use CodeKandis\HotDoc\Frontend\Templates\Generators\BookDropdownHtmlGenerator;
use CodeKandis\HotDoc\Frontend\Templates\Generators\ChapterListHtmlGenerator;
use CodeKandis\HotDoc\Frontend\Templates\Generators\SignedInHeaderContentGenerator;
use function sprintf;

/**
 * @var UserEntityInterface $signedInUser
 */
$signedInUser = $this->data[ 'signedInUser' ];

/**
 * @var BookEntityCollectionInterface $books
 */
$books = $this->data[ 'books' ];

/**
 * @var BookEntityInterface $requestedBook
 */
$requestedBook = $this->data[ 'requestedBook' ];

$chapterList = ( new ChapterListHtmlGenerator( $requestedBook->getChapters(), null ) )
	->generate();

$headerContent = ( new SignedInHeaderContentGenerator(
	$signedInUser,
	new FrontendUriBuilder(
		FrontendConfigurationRegistry
			::_()
			->getUriBuilderConfiguration()
	)
) )
	->generate();

$contentContent = sprintf(
	<<<END
		<h1>%s</h1>
		%s
	END,
	$requestedBook->getName(),
	$chapterList
);

$sidebarLeftContent = sprintf(
	<<<END
		<h2>Books</h2>
		%s
		%s
	END,
	( new BookDropdownHtmlGenerator( $books, $requestedBook ) )
		->generate(),
	$chapterList
);

$additionalFollowingLinkedModularJavaScripts = [
	'/assets/js/application/Pages/ShowBook.js'
];

$additionalFollowingLinkedStylesheets = [
	'/assets/css/content.css'
];

require __DIR__ . '/Common/html-document-header.phtml';
require __DIR__ . '/Common/html-document-body.phtml';
require __DIR__ . '/Common/html-document-footer.phtml';
