<?php declare( strict_types = 1 );
namespace CodeKandis\HotDoc\Frontend\Templates\Plain\Common;

use CodeKandis\HotDoc\Environment\Entities\BookEntityInterface;
use CodeKandis\HotDoc\Environment\Entities\ChapterEntityInterface;
use CodeKandis\HotDoc\Environment\Entities\Collections\BookEntityCollectionInterface;
use CodeKandis\HotDoc\Frontend\Templates\Generators\BookSelectHtmlGenerator;
use CodeKandis\HotDoc\Frontend\Templates\Generators\ChapterListHtmlGenerator;
use CodeKandis\JsonCodec\JsonEncoder;
use CodeKandis\JsonCodec\JsonEncoderOptions;
use ParsedownToC;
use function file_get_contents;
use function sprintf;

/**
 * @var BookEntityCollectionInterface $books
 */
$books = $this->data[ 'books' ];

/**
 * @var BookEntityInterface $requestedBook
 */
$requestedBook = $this->data[ 'requestedBook' ];

/**
 * @var ChapterEntityInterface $requestedChapter
 */
$requestedChapter = $this->data[ 'requestedChapter' ];

$parsedownToC = new ParsedownToC();

$contentContent = $parsedownToC->text(
	file_get_contents(
		sprintf(
			'%s.md',
			$this->data[ 'documentPath' ]
		)
	)
);

$sidebarLeftContent = sprintf(
	<<<END
		<h2>Books</h2>
		%s
		%s
	END,
	( new BookSelectHtmlGenerator( $books, $requestedBook ) )
		->generate(),
	( new ChapterListHtmlGenerator( $requestedBook->getChapters(), $requestedChapter ) )
		->generate()
);

$sidebarRightContent = sprintf(
	<<<END
		<h2>Table Of Contents</h2>
		%s
	END,
	$parsedownToC->contentsList()
);

$booksJsonData = ( new JsonEncoder() )
	->encode(
		$books,
		new JsonEncoderOptions( JsonEncoderOptions::PRETTY_PRINT )
	);

$additionalFollowingLinkedModularJavaScripts = [
	'/assets/js/application/Pages/ShowBook.js'
];
$additionalPrecedingInlineJavaScripts        = [
	<<<END
		const books = {$booksJsonData};
	END
];

$additionalFollowingLinkedStylesheets = [
	'/assets/css/markdown.css'
];

require __DIR__ . '/Common/html-document-header.phtml';
require __DIR__ . '/Common/html-document-body.phtml';
require __DIR__ . '/Common/html-document-footer.phtml';
